# Install perfsonar roles
- src: https://github.com/perfsonar/ansible-role-perfsonar-installer
- src: https://github.com/perfsonar/ansible-role-perfsonar-testpoint
- src: https://github.com/UMNET-perfSONAR/ansible-role-rabbitmq.git
- src: https://github.com/UMNET-perfSONAR/ansible-role-pssid.git
